# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: simplesyrup_development
  username: postgres
  password: password

test:
  <<: *default
  database: simplesyrup_test
  username: postgres
  password: password

production:
  <<: *default
  database: simplesyrup_production
  username:
  password:
